//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venue.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class show
    {
        public int showId { get; set; }
        public string performer { get; set; }
        public string genre { get; set; }
        public string dates { get; set; }
        public string times { get; set; }
    }
}
